# Generated by Django 4.2.7 on 2023-11-30 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='Task_List',
        ),
    ]
